### PR TITLE
[OPTIMIZATION] Specific process optimization

### PR DESCRIPTION
**Pull request by Mxrcon**
# [OPTIMIZATION] Specific process optimization

Hey @abhi18av, based on the report that you send me for dandrea execution I'm suggesting new specifications to each process, we could discuss it here.

## PR content:
* new memory and cpu specifications to processes

## Ending

Feel free to ask  me anything, to criticize and discuss my changes here, I'm at your disposal to make any changes on this PR.
Hope we have a merge!

### CODE REVIEW

**Review by abhi18av — APPROVED** [review]
Thanks @Mxrcon , this makes sense!

**Comment by Mxrcon** [comment]
@abhi18av If it makes sense to you, I'll raise PR against our other work. :smile:

**Comment by abhi18av** [comment]
Sure, I think it's good to go.

Though for unique processes there, you might want to run the execution there once.

**Comment by Mxrcon** [comment]
@abhi18av I'll just setup gatkjar on the servers and proceed with a run of our work on the pipelines

**Pull request merged**
